Dev
Miixo22/Portfolio pull request #2
Opened 2024-12-04 14:22 UTC by Miixo22

Added a chatbot, which gives details about my portfolio.

2024-12-04 14:33 UTC, Mpho-CapaCiTi requested changes
You forgot to add chatbot responses for contact information

2024-12-05 07:15 UTC, Mpho-CapaCiTi approved these changes
Looks perfect

2024-12-05 13:00 UTC, Mbukwana approved these changes

2024-12-05 13:03 UTC, thaboxan approved these changes
looks good

2024-12-05 13:05 UTC, merged